site_name: Hestvatnet rundt
site_url: https://hestvatnet-rundt.no
copyright: Copyright &copy; 2024 Furusjøen-Hestvatnet Løypeforening
theme:
  name: material
  icon:
    logo: fontawesome/solid/person-skiing-nordic
  palette:
    primary: custom
    accent: amber
  language: nb
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kriberg/hestvatnet-rundt
markdown_extensions:
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - index.md
  - Historikk:
    - 2023: 2023.md
    - 2022: 2022.md
